let data={settings:{},bookmarks:[],history:[],downloads:[]};
const $=id=>document.getElementById(id);
function renderTabs(ts){$("tabs").innerHTML="";ts.forEach(t=>{let e=document.createElement("div");e.className="tab "+(t.active?"active":"");let s=document.createElement("span");s.className="title";s.textContent=t.title||"STY Browser";let x=document.createElement("span");x.className="x";x.textContent="×";e.append(s,x);e.onclick=ev=>ev.target===x?api.closeTab(t.id):api.switchTab(t.id);$("tabs").append(e)})}
function show(type){$("menuPanel").classList.add("hidden");$("side").classList.remove("hidden");$("sideTitle").textContent=type==="bookmarks"?"收藏夹":type==="history"?"历史记录":"下载";let arr=data[type],body=$("sideBody");body.innerHTML="";if(!arr.length){body.innerHTML='<div class="empty">暂无内容</div>';return}arr.forEach(x=>{let e=document.createElement("div");e.className="item";e.textContent=x.title||x.filename||x.url||"下载";if(type==="bookmarks"){let b=document.createElement("button");b.textContent="删除";b.onclick=async ev=>{ev.stopPropagation();data=await api.removeBookmark(x.url);show(type)};e.append(b)}if(type==="downloads"){let b=document.createElement("button");b.textContent="打开";b.onclick=()=>api.openFile(x.path);let p=document.createElement("div");p.className="progress";let bar=document.createElement("div");bar.className="bar";bar.style.width=x.total?Math.min(100,x.received/x.total*100)+"%":"100%";p.append(bar);e.append(b,p)}let sm=document.createElement("small");sm.textContent=x.url||x.path||x.time;e.append(sm);if(type!=="downloads")e.onclick=()=>{api.newTab(x.url);$("side").classList.add("hidden")};body.append(e)})}
$("newTab").onclick=()=>api.newTab();$("back").onclick=()=>api.back();$("forward").onclick=()=>api.forward();$("reload").onclick=()=>api.reload();$("home").onclick=()=>api.home?.();$("menu").onclick=()=>$("menuPanel").classList.toggle("hidden");$("sideClose").onclick=()=>$("side").classList.add("hidden");$("devtools").onclick=()=>{menuPanel.classList.add("hidden");api.devtools()};$("form").onsubmit=e=>{e.preventDefault();api.navigate($("address").value)};
$("star").onclick=async()=>{if($("address").value.startsWith("http"))data=await api.addBookmark({url:$("address").value,title:document.title})};
document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>show(b.dataset.panel));
$("settings").onclick=()=>{menuPanel.classList.add("hidden");showSettings()};
function showSettings(){side.classList.remove("hidden");sideTitle.textContent="设置";sideBody.innerHTML=`<div class="item"><b>启动主页</b><input id="homeSetting" value="${data.settings.home}" style="display:block;width:100%;margin-top:10px;padding:8px;background:#0f172a;color:white;border:1px solid #475569;border-radius:6px"><button id="saveSet" style="margin-top:10px;padding:8px">保存设置</button></div><div class="item"><b>搜索引擎</b><small>当前：Google</small></div>`;$("saveSet").onclick=async()=>{data=await api.saveSettings({home:$("homeSetting").value});alert("设置已保存")}}
api.onTabs(renderTabs);api.onTab(t=>{$("address").value=t.url||"";document.title=(t.title||"STY Browser")+" - STY Browser"});api.onData(d=>{data=d});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="t"){e.preventDefault();api.newTab()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="w"){e.preventDefault()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="l"){e.preventDefault();address.focus();address.select()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"){e.preventDefault();star.click()}if(e.key==="F12"){e.preventDefault();api.devtools()}});