const $=id=>document.getElementById(id);let bookmarks=[],history=[];
function tabs(data){$("tabs").innerHTML="";data.forEach(t=>{const e=document.createElement("div");e.className="tab "+(t.active?"active":"");const s=document.createElement("span");s.className="tab-title";s.textContent=t.title||"新标签页";const c=document.createElement("span");c.className="close";c.textContent="×";e.append(s,c);e.onclick=x=>x.target===c?browserAPI.closeTab(t.id):browserAPI.activateTab(t.id);$("tabs").append(e);});}
function showPanel(type){$("menu").classList.add("hidden");$("panel").classList.remove("hidden");$("panelTitle").textContent=type==="bookmarks"?"收藏夹":"历史记录";const body=$("panelBody");const data=type==="bookmarks"?bookmarks:history;body.innerHTML="";if(!data.length){body.innerHTML='<div class="empty">暂无记录</div>';return}data.forEach(x=>{const e=document.createElement("div");e.className="item";e.textContent=x.title||x.url;e.title=x.url;const sm=document.createElement("small");sm.textContent=x.url;e.append(sm);e.onclick=()=>{browserAPI.openUrl(x.url);$("panel").classList.add("hidden")};body.append(e);});}
$("addressForm").onsubmit=e=>{e.preventDefault();browserAPI.navigate($("address").value)};
$("newTab").onclick=()=>browserAPI.newTab();$("back").onclick=()=>browserAPI.back();$("forward").onclick=()=>browserAPI.forward();$("reload").onclick=()=>browserAPI.reload();$("downloads").onclick=()=>browserAPI.downloads();
$("menuBtn").onclick=()=>$("menu").classList.toggle("hidden");$("bookmarksMenu").onclick=()=>showPanel("bookmarks");$("historyMenu").onclick=()=>showPanel("history");$("devtools").onclick=()=>{menu.classList.add("hidden");browserAPI.devtools()};$("downloadsMenu").onclick=()=>browserAPI.downloads();$("closePanel").onclick=()=>$("panel").classList.add("hidden");
$("bookmark").onclick=async()=>{const url=$("address").value;if(!url)return;bookmarks=await browserAPI.addBookmark({url,title:document.title.replace(" - STY Browser","")||url});};
browserAPI.onTabsUpdated(tabs);
browserAPI.onTabState(s=>{$("address").value=s.url||"";document.title=(s.title||"STY Browser")+" - STY Browser";if(s.url&&/^https?:/.test(s.url)){const item={url:s.url,title:s.title||s.url,time:new Date().toISOString()};history=[item,...history.filter(x=>x.url!==s.url)].slice(0,500);/* renderer copy; persistence is added on next revision */}});
browserAPI.onInitialData(d=>{bookmarks=d.bookmarks||[];history=d.history||[]});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="l"){e.preventDefault();address.focus();address.select()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="t"){e.preventDefault();browserAPI.newTab()}if(e.key==="F12"){e.preventDefault();browserAPI.devtools()}});